config/routes.rb
Rails.application.routes.draw do
  resources :db_instances, only: [:index, :show]
  resources :instances, only: [:index, :show]
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/account.rb
class Account < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/versionable.rb
module Versionable
  extend ActiveSupport::Concern

  included do
  end

  class_methods do
    def versionable(identifier_column:, version_column: "created_at")
      scope :head, -> do
        joins(%{
          INNER JOIN (
            SELECT #{identifier_column}, MAX(#{version_column}) AS #{version_column}_max
            FROM #{table_name}
            GROUP BY #{identifier_column}
          ) #{table_name}_head
          ON  #{table_name}.#{identifier_column} = #{table_name}_head.#{identifier_column}
          AND #{table_name}.#{version_column}    = #{table_name}_head.#{version_column}_max
        })
      end
    end
  end
end

app/models/db_instance.rb
class DbInstance < ApplicationRecord
end

app/models/instance.rb
class Instance < ApplicationRecord
  include Versionable
  versionable identifier_column: "instance_id", version_column: "valid_until"

  belongs_to :account

  class << self
    def head_transaction(account, region, &block)
      transaction do
        block.call
        puts "count = #{head.where(account: account, region: region).count}"
      end
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/db_instances_controller.rb
class DbInstancesController < ApplicationController
  before_action :set_db_instance, only: [:show]

  # GET /db_instances
  # GET /db_instances.json
  def index
    @db_instances = DbInstance.all
  end

  # GET /db_instances/1
  # GET /db_instances/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_db_instance
      @db_instance = DbInstance.find(params[:id])
    end

end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show]
  helper_method :sort_column, :sort_direction

  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.head
    if params[:search]
      term = "%#{params[:search]}%"
      @instances = @instances.where("name ILIKE ? OR instances.instance_id ILIKE ? OR public_ip_address ILIKE ? OR \
      private_ip_address ILIKE ? OR public_dns_name ILIKE ? OR vpc_id ILIKE ? OR subnet_id ILIKE ?",\
      term, term, term, term, term, term, term)
    end
    if params[:sort]
      @instances = @instances.order(params[:sort] + ' ' + params[:direction])
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

  private
    def sort_column
      Instance.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, params.permit(:search).merge(:sort => column, :direction => direction), {:class => css_class}
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/db_instances_helper.rb
module DbInstancesHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :account_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/dashboard/index.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">Overview <span class="sr-only">(current)</span></a>
    </li>
  </ul>
<% end %>

app/views/db_instances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Db Instances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @db_instances.each do |db_instance| %>
      <tr>
        <td><%= db_instance.name %></td>
        <td><%= link_to 'Show', db_instance %></td>
        <td><%= link_to 'Edit', edit_db_instance_path(db_instance) %></td>
        <td><%= link_to 'Destroy', db_instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Db Instance', new_db_instance_path %>

app/views/db_instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @db_instance.name %>
</p>

<%= link_to 'Edit', edit_db_instance_path(@db_instance) %> |
<%= link_to 'Back', db_instances_path %>

app/views/instances/index.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">Overview <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">New</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Updates</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Removals</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">By Account</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">By Network</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Cost Control</a>
    </li>
  </ul>
<% end %>

<h1>Instances</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sortable "instance_id", "Instance ID" %></th>
        <th><%= sortable "name" %></th>
        <th><%= sortable "instance_type", "Type" %></th>
        <th><%= sortable "account_id", "Account" %></th>
        <th><%= sortable "region", "Network" %></th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @instances.includes(:account).each do |instance| %>
        <tr>
          <td><%= link_to instance.instance_id, instance_path(instance) %></td>
          <td><%= instance.name %></td>
          <td><%= instance.instance_type %></td>
          <td><%= instance.account.name %></td>
          <td><%= instance.region %> <%= instance.vpc_id %> <%= instance.subnet_id %></td>
          <td>New</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% Instance.new.attributes.keys.each do |attr| %>
  <strong><%= attr %>:</strong>
  <%= @instance.send(attr) %><br>
  <% end %>
</p>

<%= link_to 'Back', instances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cloud Inventory Management</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
      <a class="navbar-brand" href="<%= url_for :root %>">Cloudime</a>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= url_for :root %>">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Accounts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= url_for :instances %>">Instances</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Databases</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Networks</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0" action="<%= url_for(:instances) %>">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light pt-3 pb-3">
          <%= yield :sidebar %>
        </nav>

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
          <%= yield %>
        </main>
      </div>
    </div>

  </body>
</html>